# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Narsil-Frontend"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
template: "template_toolkit"

# session engine (is it an engine?!?)
session: Storable
session_dir: /tmp/dancer-sessions


#'narsil-ws': 'http://localhost:3000/'
'narsil-ws': 'http://narsilwssb-polettix.dotcloud.com/'

plugins:
   FlashNote:
      session_hash_key: flashnote
